import{useMemo,useState}from"react";import{Heart,MapPin,Search,ShoppingBag,UserRound,ChevronRight,Truck,ShieldCheck,Zap}from"lucide-react";
type Product={id:number;title:string;price:number;oldPrice?:number;rating:number;orders:string;image:string;badge?:string};
const products:Product[]=[
{id:1,title:"Беспроводные наушники TWS Pro",price:89000,oldPrice:129000,rating:4.8,orders:"2.4k",image:"https://images.unsplash.com/photo-1606220945770-b5b6c2c55bf1?auto=format&fit=crop&w=700&q=80",badge:"−31%"},
{id:2,title:"Умные часы Ultra",price:179000,oldPrice:239000,rating:4.7,orders:"1.8k",image:"https://images.unsplash.com/photo-1523275335684-37898b6baf30?auto=format&fit=crop&w=700&q=80",badge:"Хит"},
{id:3,title:"Мини-пылесос для автомобиля",price:99000,rating:4.6,orders:"980",image:"https://images.unsplash.com/photo-1558317374-067fb5f30001?auto=format&fit=crop&w=700&q=80"},
{id:4,title:"Рюкзак городской водостойкий",price:119000,rating:4.9,orders:"3.1k",image:"https://images.unsplash.com/photo-1553062407-98eeb64c6a62?auto=format&fit=crop&w=700&q=80",badge:"Топ"},
{id:5,title:"LED-лампа для рабочего стола",price:69000,oldPrice:85000,rating:4.8,orders:"1.2k",image:"https://images.unsplash.com/photo-1507473885765-e6ed057f782c?auto=format&fit=crop&w=700&q=80"},
{id:6,title:"Органайзер для кухни",price:59000,rating:4.7,orders:"740",image:"https://images.unsplash.com/photo-1586023492125-27b2c045efd7?auto=format&fit=crop&w=700&q=80"}
];
const cats=["Электроника","Для дома","Одежда","Красота","Детям","Авто","Аксессуары","Спорт"];
const money=(n:number)=>new Intl.NumberFormat("ru-RU").format(n)+" сум";
export function App(){const[q,setQ]=useState("");const[cart,setCart]=useState(0);const[liked,setLiked]=useState<number[]>([]);const filtered=useMemo(()=>products.filter(p=>p.title.toLowerCase().includes(q.toLowerCase())),[q]);
return <div className="app"><header><div className="top"><div className="brand"><span className="brand-mark">P</span><span>Pinduoduo<span className="uz">.uz</span></span></div><div className="location"><MapPin size={17}/><div><small>Доставка в</small><b>Ташкент</b></div></div><div className="search"><Search size={20}/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Ищите товары и бренды"/><button>Найти</button></div><button className="icon-btn"><UserRound size={21}/><span>Войти</span></button><button className="icon-btn cart" onClick={()=>setCart(cart+1)}><ShoppingBag size={21}/><span>Корзина</span>{cart>0&&<i>{cart}</i>}</button></div><nav><span>Каталог</span><span>Товары из Китая</span><span>Скидки</span><span>Как заказать</span><span>Доставка</span><span>Поддержка</span></nav></header>
<main><section className="hero"><div><div className="eyebrow"><Zap size={16}/>Выгодные покупки напрямую</div><h1>Китайские товары<br/><em>по честной цене</em></h1><p>Находим товары у проверенных продавцов, считаем стоимость в сумах и доставляем в Узбекистан.</p><div className="hero-actions"><button className="primary">Начать покупки <ChevronRight size={18}/></button><button className="secondary">Как это работает</button></div><div className="trust"><span><ShieldCheck/>Безопасная оплата</span><span><Truck/>Доставка в Узбекистан</span></div></div><div className="hero-card"><div className="sale">−50%</div><img src="https://images.unsplash.com/photo-1526170375885-4d8ecf77b99f?auto=format&fit=crop&w=1000&q=80"/><div className="hero-card-copy"><b>Большая распродажа</b><span>Популярные товары недели</span></div></div></section>
<section className="section"><div className="section-head"><div><small>Быстрый выбор</small><h2>Категории</h2></div><button>Все категории <ChevronRight size={17}/></button></div><div className="categories">{cats.map((c,i)=><div className="cat" key={c}><div className={"cat-icon c"+i}>{["⌁","⌂","◈","✦","♧","⌘","◇","◎"][i]}</div><b>{c}</b></div>)}</div></section>
<section className="section"><div className="section-head"><div><small>Для вас</small><h2>Популярные товары</h2></div><button>Смотреть все <ChevronRight size={17}/></button></div><div className="grid">{filtered.map(p=><article className="product" key={p.id}><div className="photo">{p.badge&&<span className="badge">{p.badge}</span>}<button className={liked.includes(p.id)?"heart active":"heart"} onClick={()=>setLiked(x=>x.includes(p.id)?x.filter(i=>i!==p.id):[...x,p.id])}><Heart size={19} fill={liked.includes(p.id)?"currentColor":"none"}/></button><img src={p.image} loading="lazy"/></div><div className="product-body"><h3>{p.title}</h3><div className="rating">★ {p.rating} <span>· {p.orders} заказов</span></div><div className="prices"><b>{money(p.price)}</b>{p.oldPrice&&<del>{money(p.oldPrice)}</del>}</div><div className="delivery">Доставка от 7 дней</div></div></article>)}</div></section>
<section className="steps"><div><small>Просто</small><h2>Как это работает</h2></div><div className="step-grid"><div><strong>01</strong><h3>Найдите товар</h3><p>Ищите нужный товар в каталоге и сравнивайте цены.</p></div><div><strong>02</strong><h3>Оформите заказ</h3><p>Цена сразу отображается в UZS вместе с доставкой.</p></div><div><strong>03</strong><h3>Получите в Узбекистане</h3><p>Отслеживайте посылку в личном кабинете.</p></div></div></section></main><footer><div className="brand"><span className="brand-mark">P</span><span>Pinduoduo<span className="uz">.uz</span></span></div><span>© 2026 Pinduoduo Uzbekistan</span><span>Поддержка · Доставка · Условия</span></footer></div>}