import { Link } from "expo-router";
import { SafeAreaView,View,Text,TextInput,ScrollView,Pressable,StyleSheet } from "react-native";
import { Ionicons } from "@expo/vector-icons"; import { theme } from "../src/theme";
const cats=["Для дома","Электроника","Одежда","Красота","Детям","Аксессуары"];
const products=[["Умный LED-светильник","от 89 000 сум"],["Беспроводные наушники","от 129 000 сум"],["Органайзер для дома","от 49 000 сум"],["Рюкзак городской","от 159 000 сум"]];
export default function Home(){return <SafeAreaView style={s.safe}><ScrollView contentContainerStyle={s.page}>
<View style={s.top}><View><Text style={s.brand}>Pinduoduo</Text><Text style={s.sub}>Доставка в Узбекистан</Text></View><Ionicons name="notifications-outline" size={24} color={theme.ink}/></View>
<View style={s.search}><Ionicons name="search" size={20} color={theme.muted}/><TextInput placeholder="Поиск товаров" placeholderTextColor={theme.muted} style={s.input}/></View>
<View style={s.banner}><Text style={s.bannerTitle}>Товары из Китая</Text><Text style={s.bannerText}>Цены в юанях · оплата в сумах · доставка до двери</Text><Pressable style={s.bannerBtn}><Text style={s.bannerBtnText}>Смотреть товары</Text></Pressable></View>
<Text style={s.section}>Категории</Text><ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={s.row}>{cats.map(c=><View style={s.cat} key={c}><View style={s.catIcon}><Ionicons name="grid-outline" size={22} color={theme.brand}/></View><Text style={s.catText}>{c}</Text></View>)}</ScrollView>
<View style={s.sectionRow}><Text style={s.section}>Популярное</Text><Link href="/catalog" style={s.more}>Все</Link></View>
<View style={s.grid}>{products.map(([name,price])=><Link key={name} href="/product" asChild><Pressable style={s.card}><View style={s.image}><Ionicons name="image-outline" size={34} color="#C7C9CC"/></View><Text style={s.name}>{name}</Text><Text style={s.price}>{price}</Text><Text style={s.delivery}>Бесплатная доставка*</Text></Pressable></Link>)}</View>
</ScrollView><View style={s.nav}><Link href="/home"><Ionicons name="home" size={23} color={theme.brand}/></Link><Link href="/catalog"><Ionicons name="search-outline" size={23} color={theme.muted}/></Link><Link href="/cart"><Ionicons name="cart-outline" size={23} color={theme.muted}/></Link><Link href="/orders"><Ionicons name="receipt-outline" size={23} color={theme.muted}/></Link><Link href="/profile"><Ionicons name="person-outline" size={23} color={theme.muted}/></Link></View></SafeAreaView>}
const s=StyleSheet.create({safe:{flex:1,backgroundColor:theme.bg},page:{padding:16,paddingBottom:90},top:{flexDirection:"row",justifyContent:"space-between",alignItems:"center",marginBottom:16},brand:{fontSize:24,fontWeight:"800",color:theme.ink},sub:{fontSize:12,color:theme.muted,marginTop:2},search:{height:48,borderRadius:12,backgroundColor:theme.surface,flexDirection:"row",alignItems:"center",paddingHorizontal:14,marginBottom:16},input:{flex:1,marginHorizontal:8,fontSize:15},banner:{backgroundColor:theme.brand,padding:20,borderRadius:18,marginBottom:22},bannerTitle:{fontSize:22,fontWeight:"800",color:"#fff"},bannerText:{color:"#fff",opacity:.9,lineHeight:20,marginTop:6},bannerBtn:{alignSelf:"flex-start",backgroundColor:"#fff",paddingHorizontal:14,paddingVertical:9,borderRadius:10,marginTop:14},bannerBtnText:{color:theme.brand,fontWeight:"700"},section:{fontSize:19,fontWeight:"800",color:theme.ink,marginBottom:12},row:{gap:12,paddingBottom:20},cat:{width:78,alignItems:"center"},catIcon:{width:58,height:58,borderRadius:18,backgroundColor:theme.brandSoft,alignItems:"center",justifyContent:"center",marginBottom:6},catText:{fontSize:11,color:theme.ink,textAlign:"center"},sectionRow:{flexDirection:"row",justifyContent:"space-between",alignItems:"center"},more:{color:theme.brand,fontWeight:"700"},grid:{flexDirection:"row",flexWrap:"wrap",gap:12},card:{backgroundColor:theme.surface,borderRadius:16,padding:10,width:"48%"},image:{height:145,borderRadius:12,backgroundColor:"#F0F1F2",alignItems:"center",justifyContent:"center",marginBottom:9},name:{fontSize:14,fontWeight:"600",color:theme.ink,minHeight:38},price:{fontSize:16,fontWeight:"800",color:theme.brand,marginTop:4},delivery:{fontSize:10,color:theme.success,marginTop:5},nav:{position:"absolute",bottom:0,left:0,right:0,height:68,backgroundColor:"#fff",borderTopWidth:1,borderTopColor:theme.line,flexDirection:"row",justifyContent:"space-around",alignItems:"center"}});